### ISSUE TITLE
GLib.GError: g-file-error-quark: Failed to open file "gschemas.compiled": open() failed: No such file or directory

### ISSUE THREAD

**Issue by dE57R0YER** [stickster/pulsecaster#5]
Hello!
I've installed pulsecaster as it described here - https://stickster.github.io/pulsecaster/  
First I got all dependencies and then I tried to run it by calling 
`$ ./pulsecaster/pulsecaster `
or even 
`$ python3 ui.py`
In both cases I got the same error output:
```
No schema files found: doing nothing.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pulsecaster-0.9-py3.8.egg/pulsecaster/gsettings.py", line 36, in __init__
    gss = Gio.SettingsSchemaSource.new_from_directory('.', None, False)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file «./gschemas.compiled»: open() failed: No such file or directory (4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ui.py", line 97, in on_activate
    self.gsettings = PulseCasterGSettings()
  File "/usr/local/lib/python3.8/dist-packages/pulsecaster-0.9-py3.8.egg/pulsecaster/gsettings.py", line 41, in __init__
    gss = Gio.SettingsSchemaSource.new_from_directory(schemadir, None, False)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file «/usr/local/lib/python3.8/dist-packages/pulsecaster-0.9-py3.8.egg/pulsecaster/../gschemas.compiled»: open() failed: No such file or directory (4)
```
How can I fix that?
I'm not good in Python or in freedesktop standards, so for me it doesn't seems obvious.

I using Ubuntu 20.04.

**Comment by dE57R0YER** [comment]
Solved it. 
The error message 
`Failed to open file «/usr/local/lib/python3.8/dist-packages/pulsecaster-0.9-py3.8.egg/pulsecaster/../gschemas.compiled»: open() failed: No such file or directory (4)` means that there is no file with `.gschema.xml` extension which is using for files where we describe some GNOME UI settings for `pulsecaster`.
Fortunately, this suitable file is exist in `/usr/share/glib-2.0/schemas` directory, and named `org.pulsecaster.PulseCaster.gschema.xml`
So I copied this file to directory specified in ui.py error output, compiled gschema into `gschemas.compiled` and ran script again.

By these commands:

```
$ cd /usr/local/lib/python3.8/dist-packages/pulsecaster-0.9-py3.8.egg/pulsecaster/__pycache__
$ sudo cp /usr/share/glib-2.0/schemas/org.pulsecaster.PulseCaster.gschema.xml .
$ sudo glib-compile-schemas .

```
